version: '3'

services:
  debian10:
    image: debian:10
  mysql:
    container_name: mysql-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: zoo_test
      MYSQL_ROOT_PASSWORD: root
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    volumes:
      - ./docker-configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - mysql-container
      - node-exporter-container
  grafana-container:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - 3000:3000
    volumes:
      - ./docker-configs/grafana.ini:/etc/grafana.grfana.ini
    depends_on:
      - prometheus-container
  nginx-container:
    image: nginx
    container_name: nginx-container
    ports:
      - 8080:8080
    volumes:
      - ./docker-configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana-container
  node-exporter-container:
    image: prom/node-exporter
    container_name: node-exporter-container
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  gitlab-container:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-data/gitlab/config:/etc/gitlab
      - ./docker-data/gitlab/logs:/var/log/gitlab
      - ./docker-data/gitlab/data:/var/opt/gitlab
